// Code generated by goyacc - DO NOT EDIT.

package kit

import __yyfmt__ "fmt"

import (
	"fmt"
	"strconv"
	"strings"
	"text/scanner"
)

type Expression interface{}
type ParenExpr struct {
	SubExpr Expression
}
type Token struct {
	token   int
	literal string
}
type NumExpr struct {
	literal string
}
type BinOpExpr struct {
	left     NumExpr
	operator string
	right    NumExpr
}
type AssocExpr struct {
	left     Expression
	operator string
	right    Expression
}
type UnaryExpr struct {
	operator string
	right    Expression
}

type yySymType struct {
	yys   int
	token Token
	expr  Expression
}

type yyXError struct {
	state, xsym int
}

const (
	yyDefault = 57353
	yyEofCode = 57344
	AND       = 57348
	GE        = 57351
	IS        = 57350
	LE        = 57352
	NOT       = 57347
	NUMBER    = 57346
	OR        = 57349
	yyErrCode = 57345

	yyMaxDepth = 200
	yyTabOfs   = -12
)

var (
	yyPrec = map[int]int{
		IS:  0,
		'<': 1,
		GE:  1,
		'>': 1,
		LE:  1,
		AND: 2,
		OR:  3,
		NOT: 4,
	}

	yyXLAT = map[int]int{
		57344: 0,  // $end (12x)
		57348: 1,  // AND (12x)
		57349: 2,  // OR (12x)
		41:    3,  // ')' (11x)
		57346: 4,  // NUMBER (10x)
		40:    5,  // '(' (5x)
		57354: 6,  // expr (5x)
		57347: 7,  // NOT (5x)
		60:    8,  // '<' (1x)
		62:    9,  // '>' (1x)
		57351: 10, // GE (1x)
		57350: 11, // IS (1x)
		57352: 12, // LE (1x)
		57355: 13, // program (1x)
		57353: 14, // $default (0x)
		57345: 15, // error (0x)
	}

	yySymNames = []string{
		"$end",
		"AND",
		"OR",
		"')'",
		"NUMBER",
		"'('",
		"expr",
		"NOT",
		"'<'",
		"'>'",
		"GE",
		"IS",
		"LE",
		"program",
		"$default",
		"error",
	}

	yyTokenLiteralStrings = map[int]string{}

	yyReductions = map[int]struct{ xsym, components int }{
		0:  {0, 1},
		1:  {13, 1},
		2:  {6, 1},
		3:  {6, 2},
		4:  {6, 3},
		5:  {6, 3},
		6:  {6, 3},
		7:  {6, 3},
		8:  {6, 3},
		9:  {6, 3},
		10: {6, 3},
		11: {6, 3},
	}

	yyXErrors = map[yyXError]string{}

	yyParseTab = [23][]uint8{
		// 0
		{4: 15, 17, 14, 16, 13: 13},
		{12},
		{11, 19, 21},
		{10, 10, 10, 10, 8: 25, 26, 28, 27, 29},
		{4: 15, 17, 24, 16},
		// 5
		{4: 15, 17, 18, 16},
		{1: 19, 21, 20},
		{4: 15, 17, 23, 16},
		{7, 7, 7, 7},
		{4: 15, 17, 22, 16},
		// 10
		{6, 6, 6, 6},
		{8, 8, 21, 8},
		{9, 9, 9, 9},
		{4: 34},
		{4: 33},
		// 15
		{4: 32},
		{4: 31},
		{4: 30},
		{1, 1, 1, 1},
		{2, 2, 2, 2},
		// 20
		{3, 3, 3, 3},
		{4, 4, 4, 4},
		{5, 5, 5, 5},
	}
)

var yyDebug = 0

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyLexerEx interface {
	yyLexer
	Reduced(rule, state int, lval *yySymType) bool
}

func yySymName(c int) (s string) {
	x, ok := yyXLAT[c]
	if ok {
		return yySymNames[x]
	}

	if c < 0x7f {
		return __yyfmt__.Sprintf("%q", c)
	}

	return __yyfmt__.Sprintf("%d", c)
}

func yylex1(yylex yyLexer, lval *yySymType) (n int) {
	n = yylex.Lex(lval)
	if n <= 0 {
		n = yyEofCode
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("\nlex %s(%#x %d), lval: %+v\n", yySymName(n), n, n, lval)
	}
	return n
}

func yyParse(yylex yyLexer) int {
	const yyError = 15

	yyEx, _ := yylex.(yyLexerEx)
	var yyn int
	var yylval yySymType
	var yyVAL yySymType
	yyS := make([]yySymType, 200)

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yyerrok := func() {
		if yyDebug >= 2 {
			__yyfmt__.Printf("yyerrok()\n")
		}
		Errflag = 0
	}
	_ = yyerrok
	yystate := 0
	yychar := -1
	var yyxchar int
	var yyshift int
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	if yychar < 0 {
		yylval.yys = yystate
		yychar = yylex1(yylex, &yylval)
		var ok bool
		if yyxchar, ok = yyXLAT[yychar]; !ok {
			yyxchar = len(yySymNames) // > tab width
		}
	}
	if yyDebug >= 4 {
		var a []int
		for _, v := range yyS[:yyp+1] {
			a = append(a, v.yys)
		}
		__yyfmt__.Printf("state stack %v\n", a)
	}
	row := yyParseTab[yystate]
	yyn = 0
	if yyxchar < len(row) {
		if yyn = int(row[yyxchar]); yyn != 0 {
			yyn += yyTabOfs
		}
	}
	switch {
	case yyn > 0: // shift
		yychar = -1
		yyVAL = yylval
		yystate = yyn
		yyshift = yyn
		if yyDebug >= 2 {
			__yyfmt__.Printf("shift, and goto state %d\n", yystate)
		}
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	case yyn < 0: // reduce
	case yystate == 1: // accept
		if yyDebug >= 2 {
			__yyfmt__.Println("accept")
		}
		goto ret0
	}

	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			if yyDebug >= 1 {
				__yyfmt__.Printf("no action for %s in state %d\n", yySymName(yychar), yystate)
			}
			msg, ok := yyXErrors[yyXError{yystate, yyxchar}]
			if !ok {
				msg, ok = yyXErrors[yyXError{yystate, -1}]
			}
			if !ok && yyshift != 0 {
				msg, ok = yyXErrors[yyXError{yyshift, yyxchar}]
			}
			if !ok {
				msg, ok = yyXErrors[yyXError{yyshift, -1}]
			}
			if yychar > 0 {
				ls := yyTokenLiteralStrings[yychar]
				if ls == "" {
					ls = yySymName(yychar)
				}
				if ls != "" {
					switch {
					case msg == "":
						msg = __yyfmt__.Sprintf("unexpected %s", ls)
					default:
						msg = __yyfmt__.Sprintf("unexpected %s, %s", ls, msg)
					}
				}
			}
			if msg == "" {
				msg = "syntax error"
			}
			yylex.Error(msg)
			Nerrs++
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				row := yyParseTab[yyS[yyp].yys]
				if yyError < len(row) {
					yyn = int(row[yyError]) + yyTabOfs
					if yyn > 0 { // hit
						if yyDebug >= 2 {
							__yyfmt__.Printf("error recovery found error shift in state %d\n", yyS[yyp].yys)
						}
						yystate = yyn /* simulate a shift of "error" */
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery failed\n")
			}
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yySymName(yychar))
			}
			if yychar == yyEofCode {
				goto ret1
			}

			yychar = -1
			goto yynewstate /* try again in the same state */
		}
	}

	r := -yyn
	x0 := yyReductions[r]
	x, n := x0.xsym, x0.components
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= n
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	exState := yystate
	yystate = int(yyParseTab[yyS[yyp].yys][x]) + yyTabOfs
	/* reduction by production r */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce using rule %v (%s), and goto state %d\n", r, yySymNames[x], yystate)
	}

	switch r {
	case 1:
		{
			yyVAL.expr = yyS[yypt-0].expr
			yylex.(*Lexer).result = yyVAL.expr
		}
	case 2:
		{
			yyVAL.expr = NumExpr{literal: yyS[yypt-0].token.literal}
		}
	case 3:
		{
			yyVAL.expr = UnaryExpr{operator: "!", right: yyS[yypt-0].expr}
		}
	case 4:
		{
			yyVAL.expr = AssocExpr{left: yyS[yypt-2].expr, operator: "&&", right: yyS[yypt-0].expr}
		}
	case 5:
		{
			yyVAL.expr = ParenExpr{SubExpr: yyS[yypt-1].expr}
		}
	case 6:
		{
			yyVAL.expr = AssocExpr{left: yyS[yypt-2].expr, operator: "||", right: yyS[yypt-0].expr}
		}
	case 7:
		{
			yyVAL.expr = BinOpExpr{left: NumExpr{literal: yyS[yypt-2].token.literal}, operator: "<", right: NumExpr{literal: yyS[yypt-0].token.literal}}
		}
	case 8:
		{
			yyVAL.expr = BinOpExpr{left: NumExpr{literal: yyS[yypt-2].token.literal}, operator: ">", right: NumExpr{literal: yyS[yypt-0].token.literal}}
		}
	case 9:
		{
			yyVAL.expr = BinOpExpr{left: NumExpr{literal: yyS[yypt-2].token.literal}, operator: "=", right: NumExpr{literal: yyS[yypt-0].token.literal}}
		}
	case 10:
		{
			yyVAL.expr = BinOpExpr{left: NumExpr{literal: yyS[yypt-2].token.literal}, operator: ">=", right: NumExpr{literal: yyS[yypt-0].token.literal}}
		}
	case 11:
		{
			yyVAL.expr = BinOpExpr{left: NumExpr{literal: yyS[yypt-2].token.literal}, operator: "<=", right: NumExpr{literal: yyS[yypt-0].token.literal}}
		}

	}

	if yyEx != nil && yyEx.Reduced(r, exState, &yyVAL) {
		return -1
	}
	goto yystack /* stack new state and value */
}

type Lexer struct {
	scanner.Scanner
	Vars   map[string]interface{}
	result Expression
}

func (l *Lexer) Lex(lval *yySymType) int {
	token := l.Scan()
	lit := l.TokenText()
	tok := int(token)
	switch tok {
	case scanner.Int:
		tok = NUMBER
	default:
		switch lit {
		case "IS":
			tok = IS
		case "NOT":
			tok = NOT
		case "AND":
			tok = AND
		case "OR":
			tok = OR
		case "<=":
			tok = LE
		case ">=":
			tok = GE
		default:
			if v, ok := l.Vars[lit]; ok {
				switch v.(type) {
				case int:
					tok = NUMBER
					lit = strconv.Itoa(v.(int))
				}
			}
		}
	}
	lval.token = Token{token: tok, literal: lit}
	return tok
}
func (l *Lexer) Error(e string) {
	panic(e)
}
func EvalN(e Expression) int {
	switch t := e.(type) {
	case NumExpr:
		num, _ := strconv.Atoi(t.literal)
		return num
	}
	return 0
}
func Eval(e Expression) bool {
	switch t := e.(type) {
	case ParenExpr:
		fmt.Println("Sub")
		return Eval(t.SubExpr)
	case UnaryExpr:
		fmt.Println(t.operator)
		right := Eval(t.right)
		switch t.operator {
		case "!":
			return !right
		}
	case AssocExpr:
		fmt.Println("Assoc")
		left := Eval(t.left)
		right := Eval(t.right)
		switch t.operator {
		case "||":
			return left || right
		case "&&":
			return left && right
		}
	case BinOpExpr:
		fmt.Println("BinOp")
		left := EvalN(t.left)
		right := EvalN(t.right)
		switch t.operator {
		case ">":
			return left > right
		case "<":
			return left < right
		case "=":
			return left == right
		}
	default:
		fmt.Printf("unsuported expr[%+v]", t)
	}
	return false
}
func Parse(exp string, vars map[string]interface{}) bool {
	l := new(Lexer)
	l.Vars = vars
	l.Init(strings.NewReader(exp))
	yyParse(l)
	return Eval(l.result)
}
