python ..\..\..\python\migratesnap.py "All Drums_Squares.json"
python ..\..\..\python\migratesnap.py "Angle_Waves.json"
python ..\..\..\python\migratesnap.py "Aqua Hollow_Circle Trails.json"
python ..\..\..\python\migratesnap.py "Aqua_Ghosts.json"
python ..\..\..\python\migratesnap.py "Aurora_Borealis.json"
python ..\..\..\python\migratesnap.py "Baby Blue_Floaters.json"
python ..\..\..\python\migratesnap.py "Big Block_Kaleid.json"
python ..\..\..\python\migratesnap.py "Blue Dream_Kaleidoscope.json"
python ..\..\..\python\migratesnap.py "Blue Floating_Rectangles.json"
python ..\..\..\python\migratesnap.py "Blue Green_Line Clouds.json"
python ..\..\..\python\migratesnap.py "BlueLine_TriKaleid.json"
python ..\..\..\python\migratesnap.py "Burn Floating_Rectangles.json"
python ..\..\..\python\migratesnap.py "Burn_Barrels.json"
python ..\..\..\python\migratesnap.py "Burning_Blue Candles.json"
python ..\..\..\python\migratesnap.py "Burning_Candles.json"
python ..\..\..\python\migratesnap.py "Burning_Diag Quilt.json"
python ..\..\..\python\migratesnap.py "Burning_Flower.json"
python ..\..\..\python\migratesnap.py "Burning_LR Bars.json"
python ..\..\..\python\migratesnap.py "Burning_LR Color Bars.json"
python ..\..\..\python\migratesnap.py "Burning_Lined Clouds.json"
python ..\..\..\python\migratesnap.py "Cartoon_Clouds.json"
python ..\..\..\python\migratesnap.py "Circular_Inversions.json"
python ..\..\..\python\migratesnap.py "Circular_Moire.json"
python ..\..\..\python\migratesnap.py "CleanFloating_Squares.json"
python ..\..\..\python\migratesnap.py "Concentric_Squares.json"
python ..\..\..\python\migratesnap.py "Dancing_Solo Line.json"
python ..\..\..\python\migratesnap.py "Decimated Square_Outlines.json"
python ..\..\..\python\migratesnap.py "Diagonal_Glow.json"
python ..\..\..\python\migratesnap.py "Diagonal_Mirror.json"
python ..\..\..\python\migratesnap.py "Diagonal_Moire.json"
python ..\..\..\python\migratesnap.py "Eclipse_Explosions.json"
python ..\..\..\python\migratesnap.py "ElectricBlue_Puddles.json"
python ..\..\..\python\migratesnap.py "ElectricLog_Explosion.json"
python ..\..\..\python\migratesnap.py "Extreme Purple_Kaleidoscope.json"
python ..\..\..\python\migratesnap.py "Falling_Burn Squares.json"
python ..\..\..\python\migratesnap.py "Falling_Triangles.json"
python ..\..\..\python\migratesnap.py "Fire_Borealis.json"
python ..\..\..\python\migratesnap.py "Floating_Elevations.json"
python ..\..\..\python\migratesnap.py "Floating_GuitarSquares.json"
python ..\..\..\python\migratesnap.py "Floating_Rectangles.json"
python ..\..\..\python\migratesnap.py "Floating_WideTriangles.json"
python ..\..\..\python\migratesnap.py "FourSided_LayerCake.json"
python ..\..\..\python\migratesnap.py "Frantic_Triangles.json"
python ..\..\..\python\migratesnap.py "Geographic_Elevations.json"
python ..\..\..\python\migratesnap.py "Glowing_Diamond.json"
python ..\..\..\python\migratesnap.py "Graceful_Growers.json"
python ..\..\..\python\migratesnap.py "Gradient_Triangles.json"
python ..\..\..\python\migratesnap.py "Green Kaleid_Tunnel Vision.json"
python ..\..\..\python\migratesnap.py "Green Line_Quad Kaleid.json"
python ..\..\..\python\migratesnap.py "Green Magic_Kaleidoscope.json"
python ..\..\..\python\migratesnap.py "GreenGlobule_Shadows.json"
python ..\..\..\python\migratesnap.py "Hang Drum_Squares.json"
python ..\..\..\python\migratesnap.py "Horizontal_Shadow Clouds.json"
python ..\..\..\python\migratesnap.py "Intricate_GreenWaves.json"
python ..\..\..\python\migratesnap.py "Layered Swirl_Lines.json"
python ..\..\..\python\migratesnap.py "Layered Swirl_Space.json"
python ..\..\..\python\migratesnap.py "Layered Swirl_Space2.json"
python ..\..\..\python\migratesnap.py "Layered_Diamonds.json"
python ..\..\..\python\migratesnap.py "Melted Orange_Full Kaleid.json"
python ..\..\..\python\migratesnap.py "Moire_QuadLines.json"
python ..\..\..\python\migratesnap.py "Mysterious_Lines.json"
python ..\..\..\python\migratesnap.py "Orbiting_Orange.json"
python ..\..\..\python\migratesnap.py "Pastel Bursts_Melting Away.json"
python ..\..\..\python\migratesnap.py "Pixelated_Burn Squares.json"
python ..\..\..\python\migratesnap.py "Psychedelic_GraniteLayers.json"
python ..\..\..\python\migratesnap.py "Psycho_Plaid.json"
python ..\..\..\python\migratesnap.py "Pure White_Bursts.json"
python ..\..\..\python\migratesnap.py "Quad Lines_Collapsing.json"
python ..\..\..\python\migratesnap.py "Quad_Spirograph.json"
python ..\..\..\python\migratesnap.py "Quadro_WebMotion.json"
python ..\..\..\python\migratesnap.py "Quick Scat_Circles.json"
python ..\..\..\python\migratesnap.py "Quick Scat_Purple.json"
python ..\..\..\python\migratesnap.py "Rainbow_AmoebaLayers.json"
python ..\..\..\python\migratesnap.py "Rainbow_Fuzz Balls.json"
python ..\..\..\python\migratesnap.py "Rectangular_Blur.json"
python ..\..\..\python\migratesnap.py "Rectangular_Color Trails.json"
python ..\..\..\python\migratesnap.py "Rectangular_Inversions.json"
python ..\..\..\python\migratesnap.py "Rectangular_Rain.json"
python ..\..\..\python\migratesnap.py "Red Network_Of Neurons.json"
python ..\..\..\python\migratesnap.py "Red Purple_Amoeba Chirps.json"
python ..\..\..\python\migratesnap.py "Shifty_Fire Lines.json"
python ..\..\..\python\migratesnap.py "Sideways_Inversions.json"
python ..\..\..\python\migratesnap.py "Simply_Circles.json"
python ..\..\..\python\migratesnap.py "SoftPulse_SmallCircles.json"
python ..\..\..\python\migratesnap.py "Speckled_Floaters.json"
python ..\..\..\python\migratesnap.py "Square_Mallets.json"
python ..\..\..\python\migratesnap.py "Square_Moire.json"
python ..\..\..\python\migratesnap.py "Swimming_In Ovals.json"
python ..\..\..\python\migratesnap.py "Swirling Line_Shadows.json"
python ..\..\..\python\migratesnap.py "Swirly_Spirograph.json"
python ..\..\..\python\migratesnap.py "Transient_Triangles.json"
python ..\..\..\python\migratesnap.py "Triangular_Inversions.json"
python ..\..\..\python\migratesnap.py "Tridiagonal_Moire.json"
python ..\..\..\python\migratesnap.py "TwirlMatic_Floaters.json"
python ..\..\..\python\migratesnap.py "Vertical_Color Curtain.json"
python ..\..\..\python\migratesnap.py "White Ghosts_Left Right.json"
python ..\..\..\python\migratesnap.py "WhiteBall_Cascade.json"
python ..\..\..\python\migratesnap.py "White_Ghosts.json"
python ..\..\..\python\migratesnap.py "White_GhostsUpDown.json"
python ..\..\..\python\migratesnap.py "Wrightly_Red.json"
python ..\..\..\python\migratesnap.py "Yellow Green_Bass Bursts.json"
python ..\..\..\python\migratesnap.py "YellowGreen_PasDeDeux.json"
