#pragma once

#include "winsock.h"
#include "FFGLPluginSDK.h"
#include "FFGL.h"
#include "FFGLSDK.h"
#include "FFGLLog.h"
#include "glm/glm.hpp"

#include "mmsystem.h"
#include "cJSON.h"
#include "NosuchUtil.h"
#include "NosuchOscInput.h"
#include "NosuchOscUdpInput.h"
#include "osc/OscOutboundPacketStream.h"
#include "PaletteOscInput.h"
#include "NosuchException.h"
#include "Params.h"
#include "PaletteUtil.h"
#include "Region.h"
#include "Scheduler.h"
#include "TrackedCursor.h"
#include "Palette.h"
#include "PaletteHost.h"

#include "DrawQuad.h"
#include "DrawTriangle.h"
#include "NosuchColor.h"
#include "PaletteDrawer.h"
#include "Sprite.h"
