// Generated by pk, do not edit.
package player

import (
	"github.com/vizicist/palette/kit"
)
func arpeggio ( phr Kval ) {
	if ( nargs() < 1 ) {
		print ( "usage: arpeggio(phrase)" ) return
		( Phrase("''") ); } lastend = 0 ;; r = Phrase("''") ;; for ( nt in phr ) { nt.time = lastend ; r |= nt ;; d = nt.duration ;; if ( d == 0 ) { d = 1 ; }; lastend += d ;; }; r.length = lastend ;; return ( r ); };