// Generated by kk, do not edit.
package kklib

import (
	"github.com/nosuchtim/kk/kkcore"
)

 
 
 
 
 
 func arpeggio ( phr Kval ) { 
 if ( nargs() < 1 ) { 
 print ( "usage: arpeggio(phrase)" ) 
 return ( Phrase("''") ) 
  } 
 lastend = 0 
 r = Phrase("''") 
 for ( nt in phr ) { 
 nt.time = lastend 
 r |= nt 
 d = nt.duration 
 if ( d == 0 ) { 
 } d = 1 
 lastend += d 
  } 
 r.length = lastend 
 return ( r ) 
  } 
 