// Generated by kk, do not edit.
package kklib

import (
	"github.com/nosuchtim/kk/kkcore"
)
func closest ( nt Kval,scl Kval,dir Kval ) {
	if ( nargs() < 3 ) { dir = 0 }
	if ( sizeof ( scl ) == 0 ) { print ( "Hey, closest() needs some notes in the scale!" ); return ( Phrase("''") )  }
	inc = sign = 1 ; arr =  [  ] for ( n in scl ) { arr [ n.pitch % 12 ] = 1 } t = nt.pitch if ( dir != 0 ) { t += dir inc++ sign = -dir  } while ( ( !( t % 12 ) in arr ) || ( dir != 0 && dir == sign ) || t < 0 ) { t += ( sign * inc++ ) if ( t < 0 ) { dir = 1 } if ( t > 127 ) { dir = -1 } sign = -sign  } nt.pitch = t
	return ( nt ) } 