// Generated by pk, do not edit.
package kitlib

import (
	"github.com/vizicist/palette/kit"
)
func arpeggio ( phr kit.Kval ) {
	if ( kit.nargs() < 1 ) {
		print ( "usage: arpeggio(phrase)" ) ;
		 return ( kit.Phrase("''") ) } ;
		  lastend = 0 ; ; r = kit.Phrase("''") ; ; for nt := range phr { nt.time = lastend ; ; r |= nt ; ; d = nt.duration ; ; if ( d == 0 ) { d = 1 ; } ; lastend += d ; } ;
		  r.length = lastend ; ; return ( r ) };
