// Generated by pk2go, do not edit.
package kitlib

import (
	_ "github.com/vizicist/palette/kit"
)
var dummy kit.Phrase("")
func xxx (  ) { print ( "usage: arpeggio(phrase)" ) ; return ( kit.Phrase("''") ) };