// Generated by palette_pk2go, do not edit.
package kitlib

import (
	"github.com/vizicist/palette/kit"
)
var dummy kit.Phrase
func xxx (  ) kit.Kval { print ( "usage: arpeggio(phrase)" ) ; return ( kit.NewPhraseVal("''") ) };