del "All Scat_Squares.json"
del "Colored_Echoes.json"
del "Diagonal_Fantasy.json"
del "Fluorescent_Borealis.json"
del "Geographic_Travels.json"
del "Just_Wright.json"
del "Perky_Clouds.json"
del "Playful_Plucks.json"
del "Quick Scat_Circles.json"
del "Shapely_Shadows.json"
del "Simply_Mellow.json"
del "Vocal_Linescape.json"
