# "001 Acoustic Grand Piano" "Acoustic Grand Piano" is the template for the others
makesound1.sh "002 Bright Acoustic Piano" "Bright Acoustic Piano"
makesound1.sh "003 Electric Grand Piano" "Electric Grand Piano"
makesound1.sh "004 Honky-tonk Piano" "Honky-tonk Piano"
makesound1.sh "005 Electric Piano 1" "Electric Piano 1"
makesound1.sh "006 Electric Piano 2" "Electric Piano 2"
makesound1.sh "007 Harpsichord" "Harpsichord"
makesound1.sh "008 Clavinet" "Clavinet"
makesound1.sh "009 Celesta" "Celesta"
makesound1.sh "010 Glockenspiel" "Glockenspiel"
makesound1.sh "011 Music Box" "Music Box"
makesound1.sh "012 Vibraphone" "Vibraphone"
makesound1.sh "013 Marimba" "Marimba"
makesound1.sh "014 Xylophone" "Xylophone"
makesound1.sh "015 Tubular Bells" "Tubular Bells"
makesound1.sh "016 Dulcimer" "Dulcimer"
makesound1.sh "017 Drawbar Organ" "Drawbar Organ"
makesound1.sh "018 Percussive Organ" "Percussive Organ"
makesound1.sh "019 Rock Organ" "Rock Organ"
makesound1.sh "020 Church Organ" "Church Organ"
makesound1.sh "021 Reed Organ" "Reed Organ"
makesound1.sh "022 Accordion" "Accordion"
makesound1.sh "023 Harmonica" "Harmonica"
makesound1.sh "024 Tango Accordion" "Tango Accordion"
makesound1.sh "025 Acoustic Guitar (nylon)" "Acoustic Guitar (nylon)"
makesound1.sh "026 Acoustic Guitar (steel)" "Acoustic Guitar (steel)"
makesound1.sh "027 Electric Guitar (jazz)" "Electric Guitar (jazz)"
makesound1.sh "028 Electric Guitar (clean)" "Electric Guitar (clean)"
makesound1.sh "029 Electric Guitar (muted)" "Electric Guitar (muted)"
makesound1.sh "030 Overdriven Guitar" "Overdriven Guitar"
makesound1.sh "031 Distortion Guitar" "Distortion Guitar"
makesound1.sh "032 Guitar harmonics" "Guitar harmonics"
makesound1.sh "033 Acoustic Bass" "Acoustic Bass"
makesound1.sh "034 Electric Bass (finger)" "Electric Bass (finger)"
makesound1.sh "035 Electric Bass (pick)" "Electric Bass (pick)"
makesound1.sh "036 Fretless Bass" "Fretless Bass"
makesound1.sh "037 Slap Bass 1" "Slap Bass 1"
makesound1.sh "038 Slap Bass 2" "Slap Bass 2"
makesound1.sh "039 Synth Bass 1" "Synth Bass 1"
makesound1.sh "040 Synth Bass 2" "Synth Bass 2"
makesound1.sh "041 Violin" "Violin"
makesound1.sh "042 Viola" "Viola"
makesound1.sh "043 Cello" "Cello"
makesound1.sh "044 Contrabass" "Contrabass"
makesound1.sh "045 Tremolo Strings" "Tremolo Strings"
makesound1.sh "046 Pizzicato Strings" "Pizzicato Strings"
makesound1.sh "047 Orchestral Harp" "Orchestral Harp"
makesound1.sh "048 Timpani" "Timpani"
makesound1.sh "049 String Ensemble 1" "String Ensemble 1"
makesound1.sh "050 String Ensemble 2" "String Ensemble 2"
makesound1.sh "051 SynthStrings 1" "SynthStrings 1"
makesound1.sh "052 SynthStrings 2" "SynthStrings 2"
makesound1.sh "053 Choir Aahs" "Choir Aahs"
makesound1.sh "054 Voice Oohs" "Voice Oohs"
makesound1.sh "055 Synth Voice" "Synth Voice"
makesound1.sh "056 Orchestra Hit" "Orchestra Hit"
makesound1.sh "057 Trumpet" "Trumpet"
makesound1.sh "058 Trombone" "Trombone"
makesound1.sh "059 Tuba" "Tuba"
makesound1.sh "060 Muted Trumpet" "Muted Trumpet"
makesound1.sh "061 French Horn" "French Horn"
makesound1.sh "062 Brass Section" "Brass Section"
makesound1.sh "063 SynthBrass 1" "SynthBrass 1"
makesound1.sh "064 SynthBrass 2" "SynthBrass 2"
makesound1.sh "065 Soprano Sax" "Soprano Sax"
makesound1.sh "066 Alto Sax" "Alto Sax"
makesound1.sh "067 Tenor Sax" "Tenor Sax"
makesound1.sh "068 Baritone Sax" "Baritone Sax"
makesound1.sh "069 Oboe" "Oboe"
makesound1.sh "070 English Horn" "English Horn"
makesound1.sh "071 Bassoon" "Bassoon"
makesound1.sh "072 Clarinet" "Clarinet"
makesound1.sh "073 Piccolo" "Piccolo"
makesound1.sh "074 Flute" "Flute"
makesound1.sh "075 Recorder" "Recorder"
makesound1.sh "076 Pan Flute" "Pan Flute"
makesound1.sh "077 Blown Bottle" "Blown Bottle"
makesound1.sh "078 Shakuhachi" "Shakuhachi"
makesound1.sh "079 Whistle" "Whistle"
makesound1.sh "080 Ocarina" "Ocarina"
makesound1.sh "081 Lead 1 (square)" "Lead 1 (square)"
makesound1.sh "082 Lead 2 (sawtooth)" "Lead 2 (sawtooth)"
makesound1.sh "083 Lead 3 (calliope)" "Lead 3 (calliope)"
makesound1.sh "084 Lead 4 (chiff)" "Lead 4 (chiff)"
makesound1.sh "085 Lead 5 (charang)" "Lead 5 (charang)"
makesound1.sh "086 Lead 6 (voice)" "Lead 6 (voice)"
makesound1.sh "087 Lead 7 (fifths)" "Lead 7 (fifths)"
makesound1.sh "088 Lead 8 (bass + lead)" "Lead 8 (bass + lead)"
makesound1.sh "089 Pad 1 (new age)" "Pad 1 (new age)"
makesound1.sh "090 Pad 2 (warm)" "Pad 2 (warm)"
makesound1.sh "091 Pad 3 (polysynth)" "Pad 3 (polysynth)"
makesound1.sh "092 Pad 4 (choir)" "Pad 4 (choir)"
makesound1.sh "093 Pad 5 (bowed)" "Pad 5 (bowed)"
makesound1.sh "094 Pad 6 (metallic)" "Pad 6 (metallic)"
makesound1.sh "095 Pad 7 (halo)" "Pad 7 (halo)"
makesound1.sh "096 Pad 8 (sweep)" "Pad 8 (sweep)"
makesound1.sh "097 FX 1 (rain)" "FX 1 (rain)"
makesound1.sh "098 FX 2 (soundtrack)" "FX 2 (soundtrack)"
makesound1.sh "099 FX 3 (crystal)" "FX 3 (crystal)"
makesound1.sh "100 FX 4 (atmosphere)" "FX 4 (atmosphere)"
makesound1.sh "101 FX 5 (brightness)" "FX 5 (brightness)"
makesound1.sh "102 FX 6 (goblins)" "FX 6 (goblins)"
makesound1.sh "103 FX 7 (echoes)" "FX 7 (echoes)"
makesound1.sh "104 FX 8 (sci-fi)" "FX 8 (sci-fi)"
makesound1.sh "105 Sitar" "Sitar"
makesound1.sh "106 Banjo" "Banjo"
makesound1.sh "107 Shamisen" "Shamisen"
makesound1.sh "108 Koto" "Koto"
makesound1.sh "109 Kalimba" "Kalimba"
makesound1.sh "110 Bag pipe" "Bag pipe"
makesound1.sh "111 Fiddle" "Fiddle"
makesound1.sh "112 Shanai" "Shanai"
makesound1.sh "113 Tinkle Bell" "Tinkle Bell"
makesound1.sh "114 Agogo" "Agogo"
makesound1.sh "115 Steel Drums" "Steel Drums"
makesound1.sh "116 Woodblock" "Woodblock"
makesound1.sh "117 Taiko Drum" "Taiko Drum"
makesound1.sh "118 Melodic Tom" "Melodic Tom"
makesound1.sh "119 Synth Drum" "Synth Drum"
makesound1.sh "120 Reverse Cymbal" "Reverse Cymbal"
makesound1.sh "121 Guitar Fret Noise" "Guitar Fret Noise"
makesound1.sh "122 Breath Noise" "Breath Noise"
makesound1.sh "123 Seashore" "Seashore"
makesound1.sh "124 Bird Tweet" "Bird Tweet"
makesound1.sh "125 Telephone Ring" "Telephone Ring"
makesound1.sh "126 Helicopter" "Helicopter"
makesound1.sh "127 Applause" "Applause"
makesound1.sh "128 Gunshot" "Gunshot"
