python splitparams.py bank1_1 Furry_Waves
python splitparams.py bank1_2 Bold_Strokes
python splitparams.py bank1_3 Ghost_Puddles
python splitparams.py bank1_4 Melted_Crayons
python splitparams.py bank1_5 Dream_Puddles
python splitparams.py bank1_6 Endless_Colors
python splitparams.py bank1_7 Deep_Triangles
python splitparams.py bank1_8 Perky_Trails
python splitparams.py bank1_9 Plucky_Stuff
python splitparams.py bank1_10 Spiro_Graphical
python splitparams.py bank1_11 Dusty_Pools
python splitparams.py bank1_12 Full_Bodied
python splitparams.py bank2_1 River_Contours
python splitparams.py bank2_2 Smooth_Breathing
python splitparams.py bank2_3 Organic_Growth
python splitparams.py bank2_4 Complex_Kaleid
python splitparams.py bank2_5 Shape_Shards
python splitparams.py bank2_6 Infinite_Borders
python splitparams.py bank2_7 Line_Dance
python splitparams.py bank2_8 Edgy_Kaleid
python splitparams.py bank2_9 Explosive_Shapes
python splitparams.py bank2_10 Simple_Organisms
python splitparams.py bank2_11 Smooth_Dust
python splitparams.py bank2_12 Basic_Chaos
