python ..\..\..\python\migratequad.py "All Drums_Squares.json"
python ..\..\..\python\migratequad.py "All Drums_Squares.json.new"
python ..\..\..\python\migratequad.py "All Out_Kaleid.json"
python ..\..\..\python\migratequad.py "All Scat_Squares.json"
python ..\..\..\python\migratequad.py "All_Moire.json"
python ..\..\..\python\migratequad.py "All_Squares.json"
python ..\..\..\python\migratequad.py "Blue Purple_Cartoon Clouds.json"
python ..\..\..\python\migratequad.py "Bursting_With Color.json"
python ..\..\..\python\migratequad.py "Circular_Garden.json"
python ..\..\..\python\migratequad.py "Cloudy_Elevations.json"
python ..\..\..\python\migratequad.py "Colorful_Moire.json"
python ..\..\..\python\migratequad.py "Crowded_Inversions.json"
python ..\..\..\python\migratequad.py "Diagonal_Fantasy.json"
python ..\..\..\python\migratequad.py "Drifting_Rectangles.json"
python ..\..\..\python\migratequad.py "Floating_Grains.json"
python ..\..\..\python\migratequad.py "Floating_Rectangles.json"
python ..\..\..\python\migratequad.py "Full Bore_Borealis.json"
python ..\..\..\python\migratequad.py "Funky_Squares.json"
python ..\..\..\python\migratequad.py "Geographic_Travels.json"
python ..\..\..\python\migratequad.py "Green_Variety.json"
python ..\..\..\python\migratequad.py "Infinite Layers_Of Lines.json"
python ..\..\..\python\migratequad.py "Just_Wright.json"
python ..\..\..\python\migratequad.py "Kaleidoscopes_Forever.json"
python ..\..\..\python\migratequad.py "Mostly_Moire.json"
python ..\..\..\python\migratequad.py "Only_Orange.json"
python ..\..\..\python\migratequad.py "Perky_Shapes.json"
python ..\..\..\python\migratequad.py "Playful_Plucks.json"
python ..\..\..\python\migratequad.py "Quick Scat_Circles.json"
python ..\..\..\python\migratequad.py "Simply_Mellow.json"
python ..\..\..\python\migratequad.py "Spiral Moire_Universe.json"
python ..\..\..\python\migratequad.py "Square_Fantasia.json"
python ..\..\..\python\migratequad.py "Swimming In_Salmon Blue.json"
python ..\..\..\python\migratequad.py "Too Many_Triangles.json"
python ..\..\..\python\migratequad.py "Totally_Square.json"
